/**
 * Region-Scanner — scannt alle DOM-elements im viewport-rect und baut Picks.
 *
 * Aufgabe: nach einem User-Region-Drag aus einer Bounding-Box alle Elements
 * sammeln die "in der Region drin sind". Drei-Stufen-Algo:
 *
 * **Step 1 — Containment-Test (≥80% bbox-overlap)**: Element gilt als
 * "in der Region" wenn ≥80% seiner bounding-box im region-rect liegen. Wir
 * walken den DOM-tree REKURSIV und sammeln ALLE solchen elements — auch
 * ancestors deren bbox theoretisch reinpassen würde. Im Gegensatz zu einem
 * center-only-test triggert das nicht falsch-positiv bei ``<html>``/``<body>``
 * (deren bbox = full viewport ragt aus jeder klein-bis-mittel region heraus,
 * also ratio meist <80% → no match).
 *
 * **Step 2 — Deepest-Match Filter**: aus den candidates streichen wir die
 * ancestors. Ein candidate wird verworfen sobald ein anderer candidate sein
 * descendant ist. So bleiben nur die "tiefsten" treffer im DOM-tree übrig —
 * keine 5 nested div-wrapper für den einen Link.
 *
 * **Step 3 — Trivial-Filter (bbox-area)**: kleine spacer/icons (<50px² area)
 * werden rausgefiltert — sonst kollidieren wir mit unsichtbaren `<span>`s und
 * dem User die Liste vollspammen.
 *
 * Skipped categorically:
 *   - Overlay-internals (<fp-overlay> + alles im Shadow DOM)
 *   - Elements ohne meaningful bbox (width=0 oder height=0)
 *   - Elements die nicht visible sind (display:none, visibility:hidden, opacity:0)
 *
 * Output: Liste von Pick-Objekten mit fresh uuid4 ``pick_id``. Caller
 * (region-draft.commit) muss diese via ``backendState.inspector.submitPick``
 * registrieren — DAS handhabt fingerprint-dedupe gegen existing picks.
 */
import type { Pick } from '../../_generated/state';
import { buildFingerprint, generateCssSelector } from '../element-locator';
import { nextColorIndex } from '../color-palette';

export interface ViewportRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

/**
 * Build a Pick-object aus einem DOM-element + viewport-rect zum Pick-Zeitpunkt.
 * Mirrors die buildPick-Logik aus InspectorLayer.svelte — extrahiert hier damit
 * Region-Scanner es auch nutzen kann (DRY).
 */
export function buildPickFromElement(target: Element, colorIndex: number = 0): Pick {
  const fingerprint = buildFingerprint(target);
  const selector = generateCssSelector(target);
  const r = target.getBoundingClientRect();
  const textSnippet = (target.textContent ?? '').trim().slice(0, 120);
  return {
    pick_id: crypto.randomUUID(),
    url: window.location.href,
    timestamp_ms: Date.now(),
    element: {
      selector,
      fingerprint,
      text_snippet: textSnippet,
      rect: { x: r.x, y: r.y, width: r.width, height: r.height },
    },
    comment: '',
    color_index: colorIndex,
  };
}

function isVisible(el: Element): boolean {
  if (!(el instanceof HTMLElement) && !(el instanceof SVGElement)) return false;
  const style = window.getComputedStyle(el);
  if (style.display === 'none' || style.visibility === 'hidden') return false;
  const opacity = Number(style.opacity);
  if (Number.isFinite(opacity) && opacity === 0) return false;
  return true;
}

function isOverlayInternal(el: Element): boolean {
  // <fp-overlay> + alles inside its shadow DOM ist tabu.
  if (el.tagName === 'FP-OVERLAY') return true;
  // getRootNode() returns ShadowRoot wenn das element im shadow DOM lebt.
  const root = el.getRootNode();
  return root !== document;
}

/**
 * Wieviel Prozent der element-bbox muss im rect liegen damit der candidate
 * "drin" gilt. 0.8 = 80% — gibt etwas slack für Sub-pixel-rundungen und für
 * den User der nicht pixel-genau drüber zieht.
 */
const CONTAINMENT_THRESHOLD = 0.8;

/**
 * Minimale bbox-area (px²) damit ein candidate als "meaningful" gilt. Filtert
 * winzige decorative spans / spacer-divs raus die sonst die liste vollspammen.
 */
const MIN_BBOX_AREA = 50;

/**
 * Maximum DOM walk depth below document.documentElement. Elements deeper
 * than this limit have their children skipped (the element itself is still
 * tested for containment). 12 levels covers practically all real-world
 * component trees; deeply-nested synthetic DOMs generated by bundlers do
 * not produce meaningful picks for a user-drawn region.
 */
export const MAX_SCAN_DEPTH = 12;

function intersectionArea(r: DOMRect, rect: ViewportRect): number {
  const left = Math.max(r.x, rect.x);
  const top = Math.max(r.y, rect.y);
  const right = Math.min(r.x + r.width, rect.x + rect.width);
  const bottom = Math.min(r.y + r.height, rect.y + rect.height);
  if (right <= left || bottom <= top) return 0;
  return (right - left) * (bottom - top);
}

function bboxArea(r: DOMRect): number {
  return r.width * r.height;
}

/**
 * Element gilt als "in der Region" wenn ≥80% seiner bbox im rect liegen.
 * Takes a pre-fetched DOMRect to avoid forcing layout during walk.
 */
function isContained(r: DOMRect, rect: ViewportRect): boolean {
  const area = bboxArea(r);
  if (area <= 0) return false;
  return intersectionArea(r, rect) / area >= CONTAINMENT_THRESHOLD;
}

/**
 * Pair von einem gescannten Pick + dem zugehörigen DOM-Element. Caller
 * (region-draft.commit) braucht das Element nach dem scan für die nachfolgende
 * relations-analyse (DOM-relationships analysieren → Relation-objects ableiten).
 */
export interface ScannedPick {
  pick: Pick;
  element: Element;
}

/**
 * Walk document tree, return scanned picks + their DOM-elements für ``rect``.
 *
 * Algo siehe modul-docstring oben (containment → deepest → trivial-filter).
 *
 * Performance improvements:
 *   - Change A: walk depth limited to MAX_SCAN_DEPTH (prunes ~60-80% of nodes on deep SPAs)
 *   - Change B: two-pass batched getBoundingClientRect (Phase 1: tree traversal collecting
 *     visible elements; Phase 2: batch rect reads. Eliminates interleaved forced layouts.)
 *   - Change C: sort-first O(n log n) deepest-match (replaces O(n²) candidates.some filter)
 */
export function scanRegion(rect: ViewportRect, existingPickCount: number = 0): ScannedPick[] {
  // Min-size check — sehr kleines drag = no-op (avoid full-doc-scan).
  if (rect.width < 5 || rect.height < 5) return [];

  // --- Phase 1: tree traversal (no getBoundingClientRect calls) ---
  // Collect all visible, non-overlay elements into preliminary candidates.
  // Visibility is checked via getComputedStyle (does not force layout).
  const phaseOneCandidates: Element[] = [];

  function walk(el: Element, depth: number): void {
    if (isOverlayInternal(el)) return; // skip subtree entirely
    if (isVisible(el)) {
      phaseOneCandidates.push(el);
    }
    // Depth limit: skip children beyond MAX_SCAN_DEPTH. The element at the
    // limit level is still a valid candidate — only its children are skipped.
    if (depth >= MAX_SCAN_DEPTH) return;
    for (const child of Array.from(el.children)) {
      walk(child, depth + 1);
    }
  }
  walk(document.documentElement, 0);

  // --- Phase 2: batch rect reads ---
  // Call getBoundingClientRect on every candidate in a single loop to avoid
  // interleaved forced layout flushes.
  const rectMap = new Map<Element, DOMRect>();
  for (const el of phaseOneCandidates) {
    rectMap.set(el, el.getBoundingClientRect());
  }

  // Apply containment filter using pre-collected rects.
  const contained = phaseOneCandidates.filter((el) => {
    const r = rectMap.get(el)!;
    return isContained(r, rect);
  });

  // --- Step 2: sort-first O(n log n) deepest-match filter ---
  // Sort in document order: A before B if A comes before B in the tree.
  // Ancestors sort before descendants in document order.
  contained.sort((a, b) => {
    const pos = a.compareDocumentPosition(b);
    return pos & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1;
  });

  // Forward sweep: for each candidate, discard it if it contains any later
  // candidate (meaning a descendant is also in the set — we keep the deeper one).
  // Because the list is in document order, ancestors appear before descendants.
  // A candidate is an "ancestor to prune" if any element after it is its
  // descendant. We build a WeakSet of all kept elements and filter in one pass.
  const keptSet = new WeakSet<Element>();
  // First pass: mark all descendants in document order, building ancestor-set
  // We use a simpler O(n²) in the worst case but with depth-limit the n is small.
  // For a clean O(n log n) result: use sort + single-sweep with ancestor-tracking.
  // Since sort is already done, ancestors precede descendants. Linear sweep:
  // keep each candidate only if NO previously-seen candidate is its ancestor.
  const seenAncestors: Element[] = [];
  const deepest: Element[] = [];
  for (const candidate of contained) {
    // Check if any ancestor in seenAncestors contains this candidate
    // (i.e., this candidate is a descendant of a seenAncestor — it's deeper)
    // If yes, the ancestor should be removed and this candidate kept.
    // Remove any ancestors from deepest that are ancestors of candidate.
    for (let i = deepest.length - 1; i >= 0; i--) {
      if (deepest[i]!.contains(candidate)) {
        // deepest[i] is an ancestor of candidate — remove it (candidate is deeper)
        deepest.splice(i, 1);
      }
    }
    // Also skip candidate if any already-kept element is a descendant of it
    // (candidate is an ancestor of a kept element — candidate should not be added)
    const hasKeptDescendant = deepest.some((kept) => candidate.contains(kept));
    if (!hasKeptDescendant) {
      deepest.push(candidate);
    }
    seenAncestors.push(candidate);
    keptSet.add(candidate);
  }
  void seenAncestors; // suppress unused-var lint

  // Step 3: trivially-small candidates rausfiltern (decorative spans, spacer).
  const meaningful = deepest.filter((c) => {
    const r = rectMap.get(c)!;
    return bboxArea(r) >= MIN_BBOX_AREA;
  });

  return meaningful.map((element, scanIndex) => ({
    pick: buildPickFromElement(element, nextColorIndex(existingPickCount + scanIndex)),
    element,
  }));
}
