/**
 * frontprompt overlay — IIFE entry point.
 *
 * Injected via Playwright `page.add_init_script(content=overlay.iife.js)`.
 *
 * Architecture: Shadow-DOM-isolated via Svelte 5 customElement mode.
 *   - App.svelte deklariert `<svelte:options customElement="fp-overlay" />`
 *   - Beim import wird App zu einer CE-Klasse. customElements.define() in
 *     setupCustomElement() registriert sie als <fp-overlay>.
 *   - mountOverlay() erzeugt ein <fp-overlay> innerhalb des host divs;
 *     Browser baut automatisch shadow root mit allen Svelte-styles drin.
 *
 * Warum CE statt manuellem shadow DOM: Svelte emittet styles standardmäßig
 * in document.head — wäre NICHT im shadow root sichtbar. CE-Modus ist
 * Svelte's offizieller shadow-DOM-Pfad und routet styles korrekt.
 *
 * Contract with `OverlayInjector` (Python):
 *   - Creates a host element with id `__frontprompt_overlay_host__` (marker)
 *   - Sets `window.__frontprompt_overlay_ready__ = true` after successful mount
 *   - Sets `window.__frontprompt_overlay_ready__ = false` on mount error
 *   - Idempotent: re-injection on cross-origin navigation no-ops if marker exists
 *   - Deferred mount: waits for DOMContentLoaded if body not yet present
 */

import App from './App.svelte';
import { backendState } from './backend-state/backend-state.svelte';
import { overlayContext } from './services/context/overlay-context.svelte';
import { bridge, setupBridge } from './bridge/bridge.svelte';
import { eventInterceptor } from './services/event-interceptor';
import { applyHostFrameInset } from './services/host-frame';
import { isDevModeEnabled, startInteractionBlockersMonitor } from './services/interaction-blockers';
import { BUILD_SESSION } from './_generated/build-info';
import { SCHEMA_VERSION } from './schema-version';

const HOST_ID = '__frontprompt_overlay_host__';
const READY_FLAG = '__frontprompt_overlay_ready__';
const CUSTOM_ELEMENT_NAME = 'fp-overlay';
// SCHEMA_VERSION: see ./schema-version.ts

declare global {
  interface Window {
    __frontprompt_overlay_ready__?: boolean;
  }
}

function setupCustomElement(): void {
  // Idempotent — Playwright re-injects on every document_load, but
  // customElements.define throws on duplicate registration.
  if (!customElements.get(CUSTOM_ELEMENT_NAME)) {
    customElements.define(CUSTOM_ELEMENT_NAME, App as unknown as CustomElementConstructor);
  }
}

async function mountOverlay(): Promise<void> {
  // Idempotency guard — re-injection-on-navigation safety.
  if (document.getElementById(HOST_ID)) return;

  try {
    // Pre-mount state hydration: fetch authoritative state via
    // window.__fp.getState() bevor wir mount() callen. Eliminates "flash of
    // defaults" bei cross-origin navigation. Typed via generated StateSnapshot —
    // kein `as any`, kein if-else-tree pro state-feld (backendState.hydrate
    // dispatcht zentral zu allen sub-stores).
    //
    // The state seed also carries `integrity_token` (a per-session
    // 64-char hex string generated by Python's secrets.token_hex(32)).
    // We extract it here and pass it to setupBridge so the dispatcher can
    // validate all subsequent state_snapshot envelopes. The token is never
    // derivable from page JS alone — it flows Python → getState() → setupBridge.
    // If getState() returns null (cold-boot / test harness), token stays null
    // → no enforcement.
    let integrityToken: string | null = null;
    if (window.__fp?.getState) {
      try {
        const seed = await window.__fp.getState();
        if (seed) {
          backendState.hydrate(seed);
          // Extract integrity token from seed envelope (not part of StateSnapshot
          // domain model, lives at the top-level wire envelope level).
          const seedRaw = seed as unknown as Record<string, unknown>;
          if (typeof seedRaw['integrity_token'] === 'string') {
            integrityToken = seedRaw['integrity_token'];
          }
        }
      } catch (err) {
        // eslint-disable-next-line no-console
        console.warn('[frontprompt] pre-mount state fetch failed, using defaults', err);
      }
    }

    // setupBridge: migrates the Playwright-expose-function-scaffold
    // (window.__fp_internal_state_getter) onto window.__fp.getState + deletes
    // the original. After this call ONLY window.__fp is in the global namespace
    // (enforced via src/__arch__/window-fp-namespace.test.ts).
    // Second arg: integrity token for dispatch validation.
    setupBridge(SCHEMA_VERSION, integrityToken);

    // Derive the OverlayContext (page URL + current backend session id) from the
    // live main-world now that window.__fp.getState is wired. This replaces the
    // old set-once sessionInfo snapshot: the context re-reads current_session_id
    // from getState() (the only envelope carrying it) and is refreshed again on
    // every state snapshot (backend-state/sync) so the render gate can never get
    // stuck on a stale-null session id and leak foreign-session boxes.
    void overlayContext.refresh();

    setupCustomElement();

    const host = document.createElement('div');
    host.id = HOST_ID;
    host.setAttribute('data-frontprompt', 'overlay');
    // Host must be position:fixed to overlay the page.
    // ALL CSS protections (opacity, color, font) live INSIDE the shadow root
    // (via Svelte CE mode), so we only need positioning + z-index here.
    // The `all: revert` on the host itself protects against host-page `* {...}`
    // rules trying to inherit into us (e.g. example.com's `div { opacity: 0.8 }`
    // matches the host div — without revert, the entire CE inside is affected).
    host.style.cssText = [
      'all: revert',
      'position: fixed',
      'inset: 0',
      'pointer-events: none',
      'z-index: 2147483647',
      'opacity: 1',
      'display: block',
    ].join('; ');

    // <fp-overlay> als child der host div. Browser baut automatisch shadow root.
    // pointer-events: none am host wird durch pointer-events: auto auf den
    // panel-elements (im shadow) gerichtet überschrieben — kein conflict weil
    // shadow-elements können ihre eigenen pointer-events haben.
    const ce = document.createElement(CUSTOM_ELEMENT_NAME);
    // Auch das CE element selbst gegen host-page-styles schützen
    ce.style.cssText = [
      'all: revert',
      'display: block',
      'width: 100%',
      'height: 100%',
      'opacity: 1',
    ].join('; ');
    host.appendChild(ce);

    // Mount-target: documentElement (=<html>) statt document.body.
    //
    // Reason: Modern MD-style modal dialogs (Google consent, Material UI, etc.)
    // set `<body inert>` to disable background interaction. `inert` is inherited
    // by ALL flat-tree-descendants — incl. customElement-host's shadow root.
    // Folge: textarea inside fp-overlay wird unfocusable + keystrokes verworfen,
    // OBWOHL der user noch clicken kann (clicks lösen pick-mode aus, aber jeder
    // input-event in shadow DOM stirbt). Wir können nicht "opt out" von inert
    // im inert-subtree.
    //
    // Defense: mount als sibling von <body>, direkter child von <html>.
    // Wenn nur body inert ist → wir bleiben fokussierbar. Wenn html inert ist
    // (selten) → still trapped, aber das ist eine andere Problem-Klasse.
    //
    // Side-effect-frei: position: fixed lebt unabhängig vom DOM-parent.
    document.documentElement.appendChild(host);

    // Host-Seite in den minimierten Overlay-Rahmen einrücken: der echte
    // Seiteninhalt wird VOM Overlay umrahmt ("gewrapped"), statt nur überlagert.
    // Konstanter Inset = die vier Panel-Laschen-Dicken (immer sichtbar). Panel-
    // Expansion legt sich nur drüber, schiebt den Inhalt nicht weiter. Läuft pro
    // Dokument-Load erneut (inkl. Cross-Origin-Nav), weil mountOverlay neu greift.
    applyHostFrameInset();

    // Interaction-blockers monitor (opt-in, DEV-flag gated).
    // Detected page-mechanismen die unsere overlay-interaction blocken:
    // inert ancestors, aria-hidden, focus-theft. Logs zu DevTools console.
    // Activation via DevTools: localStorage.setItem('fp-dev', '1') + reload.
    // Default off — die outputs sind dev-only.
    if (isDevModeEnabled()) {
      startInteractionBlockersMonitor(host);
    }

    // Event-interceptor: capture-phase tap auf wheel/scroll/click/pointerdown/
    // keydown. Feeds Toolbar status-pill + EventsTab. Product-feature (immer on).
    eventInterceptor.start();

    // Heartbeat-handler: closes round-trip. Echoes seq + client-side timestamp.
    // Cast: codegen emits Heartbeat.kind as optional (literal-with-default → ?),
    // so Extract<InboundMessage, {kind:'heartbeat'}> resolves to never. Manual cast.
    bridge.on('heartbeat', (msg) => {
      const heartbeat = msg as { seq: number };
      void bridge.send({
        kind: 'heartbeat_ack',
        schema_version: SCHEMA_VERSION,
        heartbeat_seq: heartbeat.seq,
        client_recv_time_ms: Date.now(),
      });
    });

    // Fire-and-forget initial OverlayReady. Async aber synchron-getriggered.
    // Wenn bridge.send failed (kein window.__fp), wird der error im interceptor sichtbar.
    void bridge
      .send({
        kind: 'overlay_ready',
        schema_version: SCHEMA_VERSION,
        bundle_build_session: BUILD_SESSION,
      })
      .catch((err) => {
        // eslint-disable-next-line no-console
        console.error('[frontprompt overlay] OverlayReady send failed:', err);
      });

    window[READY_FLAG] = true;
  } catch (err) {
    window[READY_FLAG] = false;
    // eslint-disable-next-line no-console
    console.error('[frontprompt overlay] mount failed:', err);
  }
}

// `add_init_script` runs at document_start — <body> doesn't exist yet.
// Defer mount until DOMContentLoaded; in re-injection-after-navigation cases,
// readyState is already 'interactive' or 'complete' and we mount immediately.
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => void mountOverlay(), { once: true });
} else {
  void mountOverlay();
}
